"""Write a one-line Python generator or iterator expression that returns the sequence 
of increasing integers generated by repeatedly adding the ascii values of each letter 
in the word “Close” to itself. 67, 175, 286,
"""

def solution():
    gen = [ord(letter) for letter in "Close"]
    # Still generating problem for var - 1
    # var = [num + var[-1] if idx > 0 else num for idx, num in enumerate(gen)]

def solution_1():
    gen = [ord(letter) for letter in "Close"]
    var = []

    for idx, num in enumerate(gen):
        if idx > 0:
            _prev = var[-1]
            _ans = num + _prev
            var.append(_ans)
        else:
            var.append(num)

    return var

